version: '3.8'
services:
  gateway:
    build: ./gateway
    ports:
      - "8080:8080"
    depends_on:
      - auth
      - user
      - billing
    environment:
      - AUTH_SERVICE_URL=http://auth:8000
      - USER_SERVICE_URL=http://user:8001
      - BILLING_SERVICE_URL=http://billing:8002
  
  auth:
    build: ./auth-service
    ports:
      - "8000:8000"
  
  user:
    build: ./user-service
    ports:
      - "8001:8001"

  billing:
    build: ./billing-service
    ports:
      - "8002:8002"
